### ISSUE TITLE
Add more colorscheme

### ISSUE THREAD

**Issue by NarutoXY** [ThemerCorp/themer.lua#3]
Only one colorscheme so far eww

Add these
- [x] Nord

- [x] Gruvbox Material
- [x] Tokyonight
- [x] Tokyodark
- [x] Rose Pine
- [x] Dracula
- [x] JavaCafe
- [x] One Dark
- [x] Papa Darker
- [x] Everforest
- [x] Doom One
- [x] Catppuccin updated
- [x] Kangwana
- [ ] GitHub dark
- [ ] Dark plus
- [ ] Doombox
- [ ] Iceberg
- [ ] VSCode Material
- [x] Darknight
- [ ] Night Lamp
- [x] Monokai
- [ ] Sonokai

**Comment by max397574** [comment]
I think I'll do one dark
just so nobody is working for nothing

**Comment by max397574** [comment]
Everforest next

**Comment by NarutoXY** [comment]
Time to check up javacafe and tokyodark

**Comment by JavaCafe01** [comment]
I can do JavaCafe :smile:

**Comment by TarunDaCoder** [comment]
#33

**Comment by TarunDaCoder** [comment]
I've added monokai

**Comment by TarunDaCoder** [comment]
I guess I'll add tokyonight too

**Comment by bryant-the-coder** [comment]
wot about ayu?
