### ISSUE TITLE
Improve diff support

### ISSUE THREAD

**Issue by bockel** [ThemerCorp/themer.lua#39]
When using the kanagawa theme with fugitive, the diffs are not properly highlighted per themer diff settings.
While themer does set DiffAdd, DiffChange, DiffDelete, these do not appear to be linked to override the [syntax/diff.vim](https://github.com/neovim/neovim/blob/master/runtime/syntax/diff.vim) defaults of diffAdded, diffRemoved, diffChanged as included from other plugins such as [vim-fugitive](https://github.com/tpope/vim-fugitive/blob/master/syntax/fugitive.vim).

I've addressed it in my local config with the following, but it should probably be merged into `mapper.lua` as it appears to apply to all themes:

```lua
		use({
			"themercorp/themer.lua",
			config = function()
				require("themer").setup({
					colorscheme = "kanagawa",
					remaps = {
						highlights = {
							globals = {
								base = {
									DiffAdd = {
										fg = "NONE",
									},
									DiffChange = {
										fg = "NONE",
									},
									DiffDelete = {
										fg = "NONE",
									},
									diffAdded = {
										link = "DiffAdd",
									},
									diffRemoved = {
										link = "DiffDelete",
									},
									diffChanged = {
										link = "DiffChange",
									},
								},
							},
						},
					},
				})
			end,
		})
```

Since syntax/diff.vim sets the fg color and themer sets the bg, I needed to disable the original fg highlights to get a more pleasing highlight.

**Comment by bryant-the-coder** [comment]
If i am not mistaken, fugitive is not yet supported. :p Use gitsigns :DD
