### ISSUE TITLE
Docs for updating base highlights are wrong

### ISSUE THREAD

**Issue by bellini666** [ThemerCorp/themer.lua#49]
Previously to replace base highlights, one would need to pass `remaps.highlights.base` with the highlights in it. Now it seems that doesn't require `base` anymore.

Either this is an unwanted change, or the docs need to be updated.

**Comment by bellini666** [comment]
On a related note here, I did [this change](https://github.com/ThemerCorp/themer.lua/commit/2f5e80b7f3ab2db61dc8080130f460937051092a) to fix wrong jellybeans mapping, but after it got merged I tried removing my own remap but it did not make any effect.

Is that not the way to do that?

**Comment by bryant-the-coder** [comment]
hey @bellini666 , astro is resting for the moment. please be patient

**Comment by bellini666** [comment]
@bryant-the-coder didn't want to cause the impression of being "impatient", just making sure an issue gets reports.

**Comment by bryant-the-coder** [comment]
sorry •́  ‿ ,•̀, i think i misunderstood your previous comment.

**Comment by NarutoXY** [comment]
> Either this is an unwanted change, or the docs need to be updated.
Ah yes, it is intentional (sorry i forgot to update docs)
It was discussed in the discord server.

I did this because many times it was like meh to go and look in source code of the mapper and then remap as per the name of table, I felt it would be good to remove the verbose nature of remaps

**Comment by NarutoXY** [comment]
the new style gave some problems so reverted to old one and pr is merged #53

**Comment by NarutoXY** [comment]
jellybeans should be fixed now. closing this issue

**Comment by NarutoXY** [comment]
@bellini666 fixed with latest commit in main branch

**Comment by bellini666** [comment]
@NarutoXY indeed fixed! Thank you :)
