### ISSUE TITLE
Seeing E484: Can't open file ~/.local/share/nvim/themer

### ISSUE THREAD

**Issue by bellini666** [ThemerCorp/themer.lua#50]
After updating today, I'm seeing `E484: Can't open file ~/.local/share/nvim/themer` as soon as I open my neovim.

**Comment by bockel** [comment]
I'm seeing it too. May have something to do with telescope.
When installed with packer, the themer directory is `~/.local/share/nvim/site/pack/packer/*/themer.lua`.

There is no `themer` file or folder at `~/.local/share/nvim/themer`.
Looking through the code, it isn't immediately clear what is looking for the file nor what is expected to be at that location.

**Comment by typkrft** [comment]
I'm assuming it's [this](https://github.com/ThemerCorp/themer.lua/blob/e83769d95bf36ef11c4d218bf1fb87e649876479/lua/themer/modules/installer/utils.lua#L2) or [this](https://github.com/ThemerCorp/themer.lua/blob/e83769d95bf36ef11c4d218bf1fb87e649876479/lua/themer/modules/installer/load_installed.lua#L3) But I'm also not sure what they are looking for or what it should be.

**Comment by TarunDaCoder** [comment]
Hey @bellini666 @bockel and @typkrft ,
A temporary fix is to create the `themer` folder manually inside `stdpath('data')`
On Windows: `C:\Users\<username>\AppData\Local\nvim-data
On Linux: `~/.local/nvim`

**Comment by NarutoXY** [comment]
@TarunDaCoder @bellini666 @bockel @typkrft check this issue with the dev branch, i pushed a probable fix in #54.

**Comment by NarutoXY** [comment]
pr #54 merged
