### ISSUE TITLE
how to add custom highlights

### ISSUE THREAD

**Issue by CRAG666** [ThemerCorp/themer.lua#52]
I want to change the look of the telescope completely and I need to be able to add something like this in this plugin:

				utils.fg_bg("TelescopeBorder", "#1a1a2e", "NONE")
				utils.fg_bg("TelescopePromptBorder", "NONE", "NONE")
				utils.fg_bg("TelescopePromptNormal", "white", "NONE")
				utils.fg_bg("TelescopePromptPrefix", "#84c49b", "NONE")

				utils.fg_bg("TelescopePromptTitle", "black", "#fb5c8e")
				utils.fg_bg("TelescopePreviewTitle", "black", "#a29dff")
				utils.fg_bg("TelescopeResultsTitle", "black", "#f79f79")

				utils.bg("TelescopeResults", "NONE")
				utils.bg("TelescopeNormal", "NONE")
				utils.bg("TelescopeSelection", "#565393")

**Comment by bryant-the-coder** [comment]
does it work?

**Comment by bryant-the-coder** [comment]
currenly @NarutoXY is on break after making this plugin... he may take some time to reply. you can join the discord server if u wanna ask ques

**Comment by NarutoXY** [comment]
yes you can very well do this with sth like
```lua
require("themer").setup({
	remaps = {
	highlights = {
		globals = {
			plugins = {
				telescope = {
					TelescopeBorder = { fg = "#1a1a2e", bg = "NONE" },
					TelescopePromptBorder = { fg = "NONE", bg = "NONE" },
					TelescopePromptNormal = { fg = "white", bg = "NONE" },
					TelescopePromptPrefix = { fg = "#84c49b", bg = "NONE" },
					
					TelescopePromptTitle = { fg = "black", bg = "#fb5c8e" },
					TelescopePreviewTitle = { fg = "black", bg = "#a29dff" },
					TelescopeResultsTitle = { fg = "black", bg = "#f79f79" },
					
					TelescopeResults = { bg = "NONE" },
					TelescopeNormal = { bg = "NONE" },
					TelescopeSelection = { bg = "#565393" },
				}
			}
		}
	}
	}
})
```
