### ISSUE TITLE
Trouble with shorthand color hex codes

### ISSUE THREAD

**Issue by MarWeUMR** [ThemerCorp/themer.lua#79]
Hi,
I'm in the middle of working on my config for [heirline.lua](https://github.com/rebelot/heirline.nvim). The goal was to make heirline apply the correct colors when themer's scrollcolor function is used. I'm using _require("themer.modules.core.api").get_cp(theme_name)_ to pull the color table from themer.
Most of themer.lua's themes are working flawlessly. The issue is with those themes, having shorter hex codes specified. 
A few examples:

- [#0 in jellybeans](https://github.com/ThemerCorp/themer.lua/blob/b8f09c7a388bae6b82c39e263b7f6db1f659a34f/lua/themer/modules/themes/jellybeans.lua#L57)
- [#8b8b in ayu_mirage](https://github.com/ThemerCorp/themer.lua/blob/b8f09c7a388bae6b82c39e263b7f6db1f659a34f/lua/themer/modules/themes/ayu_mirage.lua#L54)

Where the trouble comes in is [in this call](https://github.com/rebelot/heirline.nvim/blob/bb7eaec8f5f8e762b23da91109b54e1b3518c7b8/lua/heirline/highlights.lua#L14).

The error: 

> E5108: Error executing lua ...k/packer/start/heirline.nvim/lua/heirline/highlights.lua:17: '#8b8b' is not a valid color
stack traceback:
        [C]: in function 'nvim_set_hl'
        ...k/packer/start/heirline.nvim/lua/heirline/highlights.lua:17: in function 'make_hl'
        ...k/packer/start/heirline.nvim/lua/heirline/highlights.lua:75: in function 'eval_hl'
        ...k/packer/start/heirline.nvim/lua/heirline/statusline.lua:159: in function 'eval'
        ...k/packer/start/heirline.nvim/lua/heirline/statusline.lua:175: in function 'eval'
        ...k/packer/start/heirline.nvim/lua/heirline/statusline.lua:175: in function 'eval'
        ...te/pack/packer/start/heirline.nvim/lua/heirline/init.lua:32: in function <...te/pack/packer/start/heirline.nvim/lua/heirline/init.lua:29>

Since its crashing in a neovim function I was wondering if it's just an inconsistency with the color convention themer is using.

Is there anything I'm missing or is this a specific issue of my current setup?

**Comment by NarutoXY** [comment]
Can you send your heirline config? You can do an if statement to check length of strings

**Comment by MarWeUMR** [comment]
Hey, sure. Thanks for replying.

Config: [heirline.lua config](https://pastebin.com/MebVtMsu)

The config is still a bit messy, I'm sorry for that.
Checking with an if statement was my initial plan, but than I thought why not ask first.

**Comment by NarutoXY** [comment]
Fixed :D
