### ISSUE TITLE
Catppuccino Dark will be deprecated very soon, the remastered version will replace it

### ISSUE THREAD

**Issue by Pocco81** [ThemerCorp/themer.lua#9]
Hey Naruto! Nice to meet you, came from the Reddit post. As the title says, Catppuccino Dark will soon be deprecated. I'm not sure if you have followed the development of Catppuccino, but you can find the huge discussion that led to it [here](https://github.com/Pocco81/Catppuccino.nvim/issues/44?notification_referrer_id=NT_kwDOA3ollrMyNTU4MzkxMTg2OjU4MzM2NjYy#issuecomment-954424799).

I know it's a very long discussion, so basically what has come out of it so far is Remastered Catppuccino, which is what I call a "middle ground dark theme", which means its color palette is mid-<everything> (mid-tone, mid-contrast, mid mid-saturation) unlike more "radical" themes like Dracula or Nord (they are sweet themes tho). Furthermore its main colors are pink, magenta, and fuchsia. My reasons are there but I'll make a Reddit post about it explaining why in-depth after it's officially released.

Anyhow, the problem is that, after it gets officially released, it will replace all of the current themes for consistency and ease of maintenance reasons. Catppuccino Dark will become deprecated and there will only be _Catppuccino_.

Excuse any inconveniences, if you need help I'd happily PR it myself once everything is officially released, I really like this project of yours!. [This is how it looks as of 3 days ago](https://github.com/Pocco81/Catppuccino.nvim/issues/44#issuecomment-953429791) (as dev continues, it'll keep on changing).

**Comment by NarutoXY** [comment]
Hey Pocco81, all good mate. Sorry, I was not really following with development of catppuccino. 

Ya so you are welcome to open a pr after it gets stable or ill add it myself. ngl remastered cpt is true killer. Here is the :chefkiss: for the awesome colors.

**Comment by Pocco81** [comment]
Thanks for the Cheffkiss lol.

So, I've been peeking around the source code and there are quite a lot of ports of the Rose Pine theme (I just learned about it just now so excuse me if anything of what I'm about to say is wrong). So I'll assume you really like this theme.

Just wanted to recommend you mine :) [Catppuccino](https://github.com/Pocco81/Catppuccino.nvim/issues/44#issuecomment-953429791) is simpler in composition and not quite as pale as [Rose Pine](https://github.com/rose-pine/neovim/blob/main/assets/rose-pine.png), and of course all the other characteristics I mentioned in the link, I don't know under which criteria were Rose Pine colora were picked, but I think you can vibe with it too ⁽⁽◝( •௰• )◜⁾⁾.

**Comment by NarutoXY** [comment]
Fun Fact: I added Rose Pine ports to make Danymat, one of core devs of neorg to switch to themer lol

**Comment by Pocco81** [comment]
Oh well in that case @danymat might like this :)

**Comment by danymat** [comment]
Hello @Pocco81, thank you for the ping

Indeed I really like this new theme ! Overall, I'm very happy to see that more warmer palettes are being created

**Comment by Pocco81** [comment]
Aww thanks mate! I'm really glad you liked Katppuccino (yes, the project [was rebranded](https://github.com/Pocco81/Catppuccino.nvim/issues/46))!

> I'm very happy to see that more warmer palettes

Currently it's stable enough for normal use (but please don't use it yet, I'll make sure to let you know after everything gets officially released). And btw, I got to try your favorite theme Rose Pine, it's really good! Here is a side-by-side comparison with Katppuccino as of [this commit](https://github.com/Pocco81/Catppuccino.nvim/commit/48a0a41f56378973527508d110c3215395dd2e20):

![image](https://user-images.githubusercontent.com/58336662/139606238-830c7bff-4b6f-4844-9ac0-dfc8eab01e1e.png)

(Side note: @NarutoXY yeah they are actually very different... but anyhow, you can still vibe with it right? lol)

**Comment by Pocco81** [comment]
@NarutoXY just thought I'd let you know that the theme underwent a couple of changes after [this issue](https://github.com/catppuccin/nvim/issues/56). Here is how the theme looks with various [enhancements](https://github.com/catppuccin/catppuccin/projects/1) that were requested:

(left <- catppuccin; right -> rose theme, just for @danymat to compare, because maybe he is still interested ;)

![image](https://user-images.githubusercontent.com/58336662/142793772-c0f2181e-c917-4cdc-99b7-ffbe47a317f5.png)

**Comment by danymat** [comment]
It's indeed very beautiful ! is it already out on master ?

**Comment by Pocco81** [comment]
Not yet, because of [this](https://github.com/catppuccin/nvim/issues/56#issuecomment-980467224). You can [check out this branch](https://github.com/catppuccin/nvim/tree/dev-rc) tho :+1:

**Comment by NarutoXY** [comment]
The cappuccino version is now in new palette pr so closing this issue
